bindings: add kotlin for android
Signed-off-by: Luca Vaccaro <me@lvaccaro.com>

diff --git a/bindings/makefile b/bindings/makefile
--- a/bindings/makefile
+++ b/bindings/makefile
@@ -15,7 +15,7 @@ init:
 	cargo install cbindgen
 	cargo install cargo-ndk
 
-all: swift-ios swift-darwin swift
+all: swift-ios swift-darwin swift kotlin bindings-android
 
 ios-universal: $(SOURCES)		
 	mkdir -p ./target/ios-universal/release
@@ -55,3 +55,61 @@ swift: ios-universal darwin-universal
 	cp ./target/aarch64-apple-ios/release/libotsffi.a swift/otsFFI.xcframework/ios-arm64/otsFFI.framework/otsFFI
 	cp ./target/ios-universal-sim/release/libotsffi.a swift/otsFFI.xcframework/ios-arm64_x86_64-simulator/otsFFI.framework/otsFFI
 	cp ./target/darwin-universal/release/libotsffi.a swift/otsFFI.xcframework/macos-arm64_x86_64/otsFFI.framework/otsFFI
+
+kotlin: android
+	cargo run --features=uniffi/cli --bin uniffi-bindgen generate src/ots.udl --language kotlin -o ffi/kotlin
+
+android: aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
+
+aarch64-linux-android: $(SOURCES) ndk-home
+	cargo ndk -t aarch64-linux-android -o ffi/kotlin/jniLibs build --release	
+	cp -a $(ANDROID_NDK_HOME)/toolchains/llvm/prebuilt/$(OS_NAME)-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so ffi/kotlin/jniLibs/arm64-v8a/
+
+armv7-linux-androideabi: $(SOURCES) ndk-home
+	cargo ndk -t armv7-linux-androideabi -o ffi/kotlin/jniLibs build --release
+	cp -a $(ANDROID_NDK_HOME)/toolchains/llvm/prebuilt/$(OS_NAME)-x86_64/sysroot/usr/lib/arm-linux-androideabi/libc++_shared.so ffi/kotlin/jniLibs/armeabi-v7a/
+
+i686-linux-android: $(SOURCES) ndk-home
+	cargo ndk -t i686-linux-android -o ffi/kotlin/jniLibs build --release
+	cp -a $(ANDROID_NDK_HOME)/toolchains/llvm/prebuilt/$(OS_NAME)-x86_64/sysroot/usr/lib/i686-linux-android/libc++_shared.so ffi/kotlin/jniLibs/x86/
+
+x86_64-linux-android: $(SOURCES) ndk-home
+	cargo ndk -t x86_64-linux-android -o ffi/kotlin/jniLibs build --release
+	cp -a $(ANDROID_NDK_HOME)/toolchains/llvm/prebuilt/$(OS_NAME)-x86_64/sysroot/usr/lib/x86_64-linux-android/libc++_shared.so ffi/kotlin/jniLibs/x86_64/
+
+bindings-android: kotlin
+	cp -r ffi/kotlin/jniLibs bindings-android/lib/src/main
+	cp -r ffi/kotlin/org bindings-android/lib/src/main/kotlin/
+	cd bindings-android && ./gradlew assemble
+	mkdir -p ffi/android
+	cp bindings-android/lib/build/outputs/aar/lib-release.aar ffi/android
+
+bindings-kotlin-multiplatform: ios-universal kotlin
+	mkdir -p bindings-kotlin-multiplatform/ots-kmp/src/androidMain
+	cp -r ffi/kotlin/jniLibs/ bindings-kotlin-multiplatform/ots-kmp/src/androidMain/jniLibs/
+	cp -r ffi/kmm/* bindings-kotlin-multiplatform/ots-kmp/src/
+
+	cp -r bindings-kotlin-multiplatform/ots-kmp/src/jvmMain/kotlin bindings-kotlin-multiplatform/ots-kmp/src/androidMain/
+
+	mkdir -p bindings-kotlin-multiplatform/ots-kmp/src/libs/ios-arm64/
+	mkdir -p bindings-kotlin-multiplatform/ots-kmp/src/libs/ios-simulator-arm64/
+	mkdir -p bindings-kotlin-multiplatform/ots-kmp/src/libs/ios-simulator-x64/
+
+	cp ./target/aarch64-apple-ios/release/libots.a bindings-kotlin-multiplatform/ots-kmp/src/libs/ios-arm64/
+	cp ./target/aarch64-apple-ios-sim/release/libots.a bindings-kotlin-multiplatform/ots-kmp/src/libs/ios-simulator-arm64/
+	cp ./target/x86_64-apple-ios/release/libots.a bindings-kotlin-multiplatform/ots-kmp/src/libs/ios-simulator-x64/
+	cd bindings-kotlin-multiplatform && ./gradlew :ots-kmp:assemble
+
+.PHONY: ndk-home
+ndk-home:
+	@if [ ! -d "${ANDROID_NDK_HOME}" ] ; then \
+		echo "Error: Please, set the ANDROID_NDK_HOME env variable to point to your NDK folder" ; \
+		exit 1 ; \
+	fi
+
+## clean:
+.PHONY: clean
+clean:
+	cargo clean
+	rm -rf ffi
+	rm -rf kmm
